# Generated by Django 4.2 on 2023-04-09 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('number', models.IntegerField(blank=True)),
                ('slug', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('security_name', models.CharField(blank=True, max_length=50)),
                ('parking_status', models.CharField(choices=[('KIRISH', 'Kirish'), ('CHIQISH', 'Chiqish')], default='KIRISH', max_length=10)),
                ('camera_ip_adress', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.category')),
            ],
        ),
        migrations.CreateModel(
            name='CarInParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(upload_to='media/')),
                ('price', models.FloatField(blank=True, default=3000, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parking')),
            ],
        ),
    ]
