# Generated by Django 4.2 on 2023-04-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image',
        ),
        migrations.AddField(
            model_name='picture',
            name='car_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
